// Generates src/countersAppBundle.js: a single self-contained module map that
// bundles the counter app (countersApp.js + storage.js + writethru.js +
// counter.js) and capnweb into one ES module, with only `cloudflare:workers`
// left external.
//
// The supervisor hands this to the Worker Loader, so the facet runs the *same*
// counter-app code that used to live in the COUNTER_REGISTRY Durable Object —
// now with its own isolated SQLite database, and without the supervisor or the
// facet being able to reach each other's storage.
//
// Run via the `build` command in wrangler.jsonc before `wrangler dev`/`deploy`.
import { buildSync } from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "src");

const res = buildSync({
  entryPoints: [join(src, "countersApp.js")],
  bundle: true,
  format: "esm",
  platform: "browser",
  // cloudflare:workers (DurableObject, RpcTarget) stays ambient in the facet.
  external: ["cloudflare:workers"],
  alias: {
    capnweb: join(src, "..", "node_modules/capnweb/dist/index-workers.js"),
  },
  write: false,
  outfile: "bundle.js",
});

const code = res.outputFiles[0].text;

// Each unique code version needs a unique ID, so the Worker Loader can key the
// cached Dynamic Worker. Derive it from the bundle so bumping the source (or
// the bundler) invalidates the cache — the supervisor reads this, not a hardcoded
// string.
const codeId = `counter-app-facet-${hashCode(code)}`;

const out = `// GENERATED by build-facet.mjs — do not edit by hand.
// A self-contained ES module bundle of the counter app (counter.js, storage.js,
// writethru.js, countersApp.js) + capnweb, with cloudflare:workers left external.
// This is the module map handed to the Worker Loader for the counter-app facet.

// The name of the bundle's own main module, and a codeId unique to this content,
// exported together so the loader config can reference both without hardcoding.
export const mainModule = "counters-app-bundle.js";

export const codeId = ${JSON.stringify(codeId)};

export const counterAppModule = {
  [mainModule]: ${JSON.stringify(code)},
};
`;

writeFileSync(join(src, "countersAppBundle.js"), out);
console.log(`wrote src/countersAppBundle.js (${code.length} bytes)`);

// A stable, compact hash of the bundle text (FNV-1a), so the codeId changes when
// the bundled source changes.
function hashCode(text) {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(36);
}
