/**
 * @file Generates src/countersAppBundle.js: a multi-module module map for the
 * Worker Loader. The counter-app source files (counter.js, writethru.js,
 * storage.js, countersApp.js) and capnweb's workers build are handed to the
 * loader as separate modules with real relative imports, so the runtime's
 * module registry resolves them at load time — the `new_module_registry`
 * no-bundle idea, applied to a facet. No esbuild: the only transform is
 * rewriting the bare `capnweb` specifier to a relative `./capnweb.js` so it
 * resolves inside the loader's module map; `cloudflare:workers` stays ambient.
 *
 * capnweb remains an npm dependency — the workers build is read straight from
 * node_modules, not vendored.
 *
 * Run via the `build` command in wrangler.jsonc before `wrangler dev`/`deploy`.
 *
 * XXX: no `with { type: 'text' }` yet. The new module registry recognizes but
 * rejects the `text` import attribute ("not yet supported"); only `json` is
 * enabled (TC39 Import Text is still Stage 3). Once it lands, this script could
 * disappear in favor of `import src from './counter.js' with { type: 'text' }`
 * in src/index.js, and the generated src/countersAppBundle.js with it. The
 * Worker Loader needs module source as strings (it compiles them into a fresh,
 * isolated facet), so today we have to emit them here.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "src");

// The app's own files, keyed by the module name the Worker Loader will resolve
// them under. Relative imports between them (`./storage.js`, `./counter.js`,
// `./writethru.js`) already match these keys, so only `capnweb` needs a rewrite.
const appFiles = ["counter.js", "ocapn.js", "writethru.js", "storage.js", "countersApp.js"];

const capnwebDist = join(here, "node_modules/capnweb/dist/index-workers.js");

// Bare specifier -> relative URL, so the runtime resolves it inside the module map.
const rewriteCapnweb = (code) =>
  code.replace(/from\s+"capnweb"/g, 'from "./capnweb.js"');

const modules = {
  "capnweb.js": readFileSync(capnwebDist, "utf8"),
};
for (const f of appFiles) {
  modules[f] = rewriteCapnweb(readFileSync(join(src, f), "utf8"));
}

const mainModule = "countersApp.js";

// Each unique code version needs a unique ID, so the Worker Loader can key the
// cached Dynamic Worker. Derive it from the whole module map so bumping any
// source (or capnweb) invalidates the cache — the supervisor reads this, not a
// hardcoded string.
const codeId = `counter-app-facet-${hashCode(JSON.stringify(modules))}`;

// Emit each module's source as a template literal rather than a JSON string:
// JSON turns every newline into a 2-byte "\\n", while a template literal keeps
// it as a literal 1-byte newline, so a multi-module map gets noticeably smaller
// (the escape cost for stray backticks / "${" is dwarfed by the newline savings).
// Escape order matters: backslash first, then backtick, then "${", so the
// backslashes we add for the backtick escape are never themselves re-escaped.
const tpl = (code) =>
  `\`${code.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")}\``;

const out = `// GENERATED by build-facet.mjs — do not edit by hand.
// A multi-module map for the Worker Loader: the counter-app source files plus
// capnweb's workers build, each as its own module with real relative imports.
// The runtime's module registry resolves the graph (the new_module_registry
// no-bundle approach); the loader config references mainModule + codeId.

export const mainModule = ${tpl(mainModule)};

export const codeId = ${tpl(codeId)};

export const counterAppModule = {
${Object.entries(modules)
  .map(([name, code]) => `  [${tpl(name)}]: ${tpl(code)}`)
  .join(",\n")}
};
`;

writeFileSync(join(src, "countersAppBundle.js"), out);
console.log(
  `wrote src/countersAppBundle.js (${modules["countersApp.js"].length}+${modules["storage.js"].length}+${modules["writethru.js"].length}+${modules["counter.js"].length}+${modules["capnweb.js"].length} bytes across ${Object.keys(modules).length} modules)`
);

// A stable, compact hash of the module map (FNV-1a), so the codeId changes when
// any bundled source changes.
function hashCode(text) {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(36);
}
