name: Generate Atom Feed

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git operations

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create feed directory
        run: mkdir -p feed

      - name: Generate Atom feed
        run: node assets/atom-feed-generator.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./feed
          destination_dir: feed
